### ISSUE TITLE
Exception, could not find binding

### ISSUE THREAD

**Issue by sjcjoosten** [raychen323/calculator#4]
The root source of this error is in `match`:

```
match (BinOp oper expr1 expr2) (BinOp oper' expr1' expr2') = if oper == oper' then
    let match1 = match expr1 expr1'
        match2 = match expr2 expr2'
        in match1 ++ match2
    else []
```

What is `match expr1 expr1'` supposed to return? If you answer: a substitution, then take a look at your type again.

How would you combine two lists of potential substitutions (one has all the substitutions needed to make the left hand sides equal, the other has all the substitutions to make the right hand sides equal) in such a way that the result is again a list of potential substitutions? (to make both sides equal)

Make sure you try the law ``x + x = 2 * x`` on the expression ``3 + 4`` when you're done.

**Comment by raychen323** [comment]
We decided to use a cartesian product of the two lists of potential substitutions.
